import {
  CalendarDays,
  CreditCard,
  Headphones,
  House,
  LayoutGrid,
  LogIn,
  Megaphone,
  MessageSquare,
  Recycle,
  Smartphone,
  Star,
  UserCheck,
  UserRound,
  UserRoundPlus,
} from "lucide-react";

import { MenuItem } from "./types";

export const menuData: MenuItem[] = [
  {
    id: "payment",
    title: "Tagihan",
    href: "/payment",
    icon: CreditCard,
    color: "green",
    isShortcut: true,
  },
  {
    id: "announcement",
    title: "Pengumuman",
    href: "/announcements",
    icon: Megaphone,
    color: "red",
    isShortcut: true,
  },
  {
    id: "event",
    title: "Agenda",
    href: "/event",
    icon: CalendarDays,
    color: "purple",
    isShortcut: true,
  },
  {
    id: "complaint",
    title: "Pengaduan",
    href: "/complaint",
    icon: MessageSquare,
    color: "blue",
    isShortcut: true,
  },
  {
    id: "asset",
    title: "Asset",
    href: "/asset",
    icon: LayoutGrid,
    color: "teal",
    isShortcut: true,
  },
  {
    id: "reward",
    title: "Poin",
    href: "/coming-soon",
    icon: Star,
    color: "yellow",
    isShortcut: true,
  },
  {
    id: "service",
    title: "Layanan",
    href: "/coming-soon",
    icon: Headphones,
    color: "green",
    isShortcut: true,
  },

  // ========= Menu lainnya =========

  {
    id: "house",
    title: "Data Rumah",
    href: "/house",
    icon: House,
    color: "green",
    isShortcut: false,
  },
  {
    id: "ppob",
    title: "PPOB",
    href: "/ppob",
    icon: Smartphone,
    color: "blue",
    isShortcut: false,
  },
  {
    id: "oil",
    title: "Minyak Jelantah",
    href: "/oil",
    icon: Recycle,
    color: "orange",
    isShortcut: false,
  },
  {
    id: "visitor",
    title: "Visitor",
    href: "/visitor",
    icon: UserRound,
    color: "teal",
    isShortcut: false,
  },
  {
    id: "invitation",
    title: "Invitation",
    href: "/invitation",
    icon: UserRoundPlus,
    color: "pink",
    isShortcut: false,
  },
  {
    id: "activation",
    title: "Aktivasi",
    href: "/activation",
    icon: UserCheck,
    color: "indigo",
    isShortcut: false,
  },
  {
    id: "login",
    title: "Login",
    href: "/login",
    icon: LogIn,
    color: "gray",
    isShortcut: false,
  },
];